### ISSUE TITLE
Faktorisieren für die Variable Title

### ISSUE THREAD

**Issue by I-Veips** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#1]
Die Variable Title in dem neuen Datensatz hat als Datentyp bis jetzt Character. Wäre es für die weitere Analyse besser dies in factor umzuwandeln, vor allem da drei Titel (Miss, Ms, Mlle) junge unverheiratete Frauen beschreiben.

**Comment by fuwatson88** [comment]
Ich würde diese Variable auch als factor umwandeln und die 3 Title mit einem Label z.B. "Miss" zusammenfassen. Außerdem würde ich vielleicht für den Titel "Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)" nur "Countess of Rothes" verwenden, weil es sonst zu lang wird.

**Comment by lisalarr** [comment]
Habe "Miss" und "Mlle" jetzt beide zu "Ms" geändert, damit das Problem mit den verschiedenen Titeln gelöst ist und zu einem Factor (mit automatisch 14 Level) umkodiert.
Ich glaube, dass wir die Kürzung des anderen Titels nicht unbedingt benötigen, da wir die Anreden ja primär zur Imputation extrahieren. Kann das bei Bedarf aber gerne noch nachholen.
