### ISSUE TITLE
(iv) Visualisierung - extraMultivariate()

### ISSUE THREAD

**Issue by I-Veips** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#13]
Uns ist aufgefallen, dass der Aufruf der Boxplot-Funktion nur für eine der beiden metrischen Variablen interpretierbar ist. Dann entspricht dies dem univariaten Boxplot aus der Funktion extraUnivariate(). Ich weiß nicht, ob dies dann redundant ist.

**Comment by fuwatson88** [comment]
Wir haben als metrische Variablen nur Ticketpreis, Alter, Anzahl der Geschwister/Ehefrauen und Anzahl der Eltern/Kinder. Mit den zwei letzten Variablen sind meiner Meinung nach keine informativen bivariaten Analysen möglich. Damit bleiben nur Ticketpreis und Alter übrig, welche wir univariat analysiert und visualisiert haben. Da die bivariaten Zusammenhänge zwischen zwei metrischen Variablen bereits in den Streudiagrammen dargestellt und mit metrBiStat() analysiert wurden, bräuchten wir denke ich keine weiteren visuellen Darstellungen mit den Boxplots.

**Comment by lisalarr** [comment]
Beim Erstellen der Funktion für die Boxplots ist mir gar nicht aufgefallen, dass wir die Darstellung bereits haben. Da gebe ich euch recht, das ist dann redundant und mit den anderen Darstellungen bereits gut abgedeckt. Ich werde das entsprechend im Code auskommentieren  :)
