### ISSUE TITLE
Discussion results

### ISSUE THREAD

**Issue by SpotAnti** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#14]
Eure Analyse der Ergebnisse ist sehr umfangreich und deckt alles Variablen ab. Ich finde ihr habt sehr gut Zusammenhänge klar gemacht. Außerdem find ich, dass es euch sehr gut gelungen die Konsistenz der rein numerischen Analysen mit den Ergebnissen, die in den Visualisierungen abzulesen sind, zu verknüpfen. 
So habt ihr zum Beispiel bei der deskriptiven Analyse des Titels der Passagiere die Ergebnisse sehr gut mit den vorherigen Ergebnissen zum Geschlecht der Passagiere hergestellt. 

Da ihre eure Ergebnisse wie gesagt sehr gut und vollumfänglich aufgeführt habt, habe ich kaum relevante neue Analysen beizutragen. Mir sind bei der Durchsicht der Analyse lediglich einige Kleinigkeiten zusätzlich noch aufgefallen:

- Im Histogramm zu den Ticketpreisen wird ersichtlich, dass sich die Ticketpreise sehr unterschiedlich gestaltet haben. Obwohl die Passagiere sich Tickets für unterschiedliche Klassen gekauft haben, so sind dennoch keine klaren disjunkte Preisklassen zu erkennen. Somit unterscheiden sich die Ticketpreise auch innerhalb derselben Klasse. Dieses Phänomen wird auch noch einmal in den Boxplots deutlich, die die Ticketpreise entsprechend der Klassen darstellen.
- Rein inhaltlich finde ich die Analyse der Preise die Verstorbene bzw. Überlebende gezahlt, haben etwas irreführend. Aus rein statistischer Sicht ist die Analyse natürlich richtig und durchführbar, aber die Interpretation erweckt den Anschein, als hätten die Passagiere, um zu überleben mehr bezahlt.  Ich denke reine inhaltlich deckt die Analyse der Verstorbenen/ Überlebenden in Bezug auf die Klasse der Reisenden ähnliche interpretatorische Ergebnisse auf.

**Comment by I-Veips** [comment]
Dankeschön : )

Zu 1): Du beziehst dich auf die deskriptive Analyse des Ticketpreis, oder? Ja, dass stimmt. Dies könnte man sehr gut noch in der Analyse des Histogramms ergänzen. Dann kann man darauf auch den Bezug auf die weitere bivariate Analysen setzen, damit wir einen roten Faden in der Analyse haben.

Zu 2): Dies kann ich nachvollziehen. Dies hängt auch stark mit den Klassen der Reisenden zusammen, da die Ticketpreise der ersten Klasse teurer waren, als die der zweiten und dritten Klasse. Auch wenn die sehr stark in den Klassen variieren, was vielleicht die Irreführung erklärt. Da mehr Menschen der ersten KLasse überlebt haben, ist der Ticketpreis der Überlebenden tendenziell höher als der, der verstorbenen. Ich stimme dir zu, dass die Analyse Überleben und Klasse der Reisenden ausreicht. Auch glaube ich, dass wenn die Klasse ein entscheidender Grund fürs Überleben war und der Ticketpreis dann in Bezug zu der Klasse steht, aber eben nicht direkt mit dem Überleben. Also haben wir da wahrscheinlich eine Scheinkorrelation vorliegen.

**Comment by SpotAnti** [comment]
Gerne doch. Vielen Dank für die Einschätzung. Ich habe die R Datei entsprechend mit Kommentaren bearbeitet.
