### ISSUE TITLE
Leeres Level für die Variable "Embarked"

### ISSUE THREAD

**Issue by fuwatson88** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#2]
Mir ist bei dem neuen Datensatz aufgefallen, dass der Faktor "Embarked" ein leeres Level beiinhaltet, sodass dieser statt drei vier Levels hat. Ist dies bei dem originalen Datensatz auch so, da ihr daran nichts geändert habt.

**Comment by lisalarr** [comment]
Ja genau, bei den Originaldaten war das ebenfalls so. 
Deswegen würde ich es einfach bei "as.factor" belassen.
