### ISSUE TITLE
2(vi) - weitere Funktionen 

### ISSUE THREAD

**Issue by lisalarr** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#3]
Ich habe bei Aufgabe 2(vi) differenziert in univariat und bivariat und mich bei beidem auf die graphische Analyse konzentriert.

Für univariat habe ich lediglich Boxplot und Dichte dargestellt, da in (v) bereits Balkendiagramme geplottet werden können.
Bei bivariat ist es ein 2x2 Gitter geworden mit Histogramm, Dichtefunktion, Boxplots und Scatterplot, damit man die Abhängigkeiten verschiedener Variablen besser erkennen kann. 

Fallen euch noch weiter sinnvolle Maße/Plots ein, die hinsichtlich der Analyse hinzugefügt werden sollten?

**Comment by SpotAnti** [comment]
Ich finde die Plots sehen sehr ordentlich aus. Ich denke es wäre aber noch sinnvoll bei extraUnivariate() eine Überprüfung einzubauen, ob es sich um ein stetiges Merkmal handelt, da ein stetige Dichte geplottet wird. Alleing schon bei dem Testaufruf mit der Variable Alter tritt schon eine Stetigkeitsannahme ein, da das Alter ja eigentlich nur auf den natürlichen Zahlen stetig verteilt ist.
Alternativ könnte auch ein Histogramm statt einer stetigen Dichte geplottet werden. Auch bei der Funktion  extraMultivariate() fehlt noch die Überprüfung auf einen stetige Variable. Vielleicht macht es hier Sinn das Stacked Histogramm und den Dichteplot gegen ein einziges Histogramm-Plot auszutauschen. 

Ansonsten fände ich noch Regressions-Visualisierung interessant. Dadurch könnte man zum Beispiel zeigen, wie das Alter den Ticketkaufpreis beeinflusst. Diese Visualisierung ist allerdings kein Muss. Mit den bereits vorhanden Funktionen haben wir denke ich bereits schon sehr viele Möglichkeiten die Daten zu analysieren.

**Comment by lisalarr** [comment]
So, kleines Update. 
Ich habe jetzt eine aktualisierte Version hochgeladen, danke für den Hinweis mit den stetigen Variablen, da hatte ich gar nicht dran gedacht als ich mit meinen konkreten Beispielen gearbeitet habe.

Um das Problem bei den univariaten Plots zu umgehen, habe ich dort nun ein Boxplot und ein Histogramm. 

Bei der multivariaten Analyse sind nun nach wie vor die Boxplots, das stacked Histogramm (weil ich persönlich die Darstellung schöner finde, je nach Variable kann man das meiner Meinung nach auch gut interpretieren) und ein lineares Regressionsmodell im Scatterplot. Dadurch ist natürlich der normale Scatterplot weg und in dem Grid sind nur noch 3 anstelle von 4 Plots, da die Dichte raus ist. 

Dokumentation habe ich soweit auch angepasst. Falls es noch Wünsche gibt oder ich was übersehen habe, gerne nochmal Bescheid geben. :) Ich glaube aber auch, dass wir vor allem mit den vorig erstellten Funktionen jetzt ein breites Spektrum abdecken können!

**Comment by I-Veips** [comment]
Mit den Funktionen können wir meiner Meinung nach eine gute Analyse der Daten machen. Sieht super aus : )
