### ISSUE TITLE
2(i) Bearbeiten der Funktion für metrische Variablen

### ISSUE THREAD

**Issue by lisalarr** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#4]
Bin gerade den Code durchgegangen und mir ist aufgefallen, dass in der Liste (unter anderem) Mittelwert ("mean") und die Zusammfassung ("summary") ausgegeben werden. 
Das ist noch sinnvoll anzupassen, da sowohl median, als auch mean in summary enthalten sind. An der Stelle wird also noch "überflüssiger" Output erzeugt.

**Comment by SpotAnti** [comment]
Stimmt, dieses ist mir auch aufgefallen. Vielleicht ist es sinnvoll den summary() Output selber zu generieren, indem noch 
quantile(x), median(x), min(x) und max(x) hinzugefügt wird. 
Die quantile()-Funktion könnte sinnvoll sein, um zu betrachten welche Altersgruppen wie stark vertreten waren.

**Comment by lisalarr** [comment]
Stimmt, das ist auch eine gute Option. Egal wie, ich denke es ist sinnvoll, dass die Werte später ohne Redundanzen ausgegeben werden, aber alle in der Interpretation berücksichtigt werden.

**Comment by fuwatson88** [comment]
Finde ich gut und würde den Vorschlag mit den einzelnen Parametern umsetzen.
