### ISSUE TITLE
Variablen Bord und Deck

### ISSUE THREAD

**Issue by SpotAnti** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#6]
Die Variablen Bord und Deck habe ich als interger Zahlen abgespeichert. Die Codierung steht in der Readme Datei. Sollen wir dieses so lassen? Ich dachte, dass das Arbeiten mit Faktoren ggf. leichter fällt. Allerdings steht auch immer explizit in der Aufgabenstellung, wenn etwas in einen Faktor umgewandelt werden soll. Deshalb bin ich mir unsicher, ob die Umcodierung letztlich als "falsch" gewertet wird.

Und falls wir dieses so lassen: Soll ich die Variablen noch in Faktoren umwandeln? (Aktuell sind sie als einfache Integer Zahlen abgespeichert).

**Comment by lisalarr** [comment]
Als falsch wird die Umkodierung nicht gewertet, wenn sie im Code (bzw. der README Datei) begründet ist, denke ich.

„Board“ und „Deck“ könnten als Factor natürlich sinnvoll sein, da die einzelnen Ausprägungen der Lage und Kabinennummern definiert sind. Das würde es in der Datenanalyse vereinfachen, die einzelnen Kategorien als diskrete Gruppen zu behandeln. 

Da wir uns so aufgeteilt hatten, dass Sam und Inken Aufgabe 4 zur Analyse bearbeiten, finde ich es sinnvoller nach deren Präferenzen zu updaten.

**Comment by I-Veips** [comment]
Ich glaube auch nicht, dass dies als falsch gewertet wird. Außerdem ist es sehr sinnvoll dies als Faktor zu speichern. Wenn wir es sogar in Aufgabe 4 analysieren wollen, benötigen wir die Variablen als Faktoren, da unsere Funktionen auf numerische oder faktorielle Datentypen ausgelegt sind. 

Wenn wir dies in der README-DAtei dokumentieren, sollte dies kein Problem sein.

**Comment by SpotAnti** [comment]
Alles klar. Die Variablen sind nun als Faktoren abgespeichert und auch die Dokumentation ist in der README Datei angepasst.
