### ISSUE TITLE
Bivariater Zusammenhang zwischen dichotomen und metrischen Variablen

### ISSUE THREAD

**Issue by fuwatson88** [lisalarr/Wissenschaftliches-Arbeiten-2023-24#9]
Für Aufgabe 4 würden wir bei der Funktion metrbistat zusätzliche t-Tests vorschlagen, um die Differenz der Mittelwerte zwischen den Gruppen (Überlebende-Nichtüberlebende) zu analysieren und um mögliche Korrelationen zwischen dichotomen und metrischen Variablen zu überprüfen. Was meint ihr dazu?

**Comment by SpotAnti** [comment]
Das klingt sinnvoll, bislang haben wir ja in der Funktion noch keine Möglichkeit die Variablen auf Korrelation zu überprüfen.
